name = "MissingsAsFalse"
uuid = "bd3c0b08-7cce-4d14-b276-b0e6d20a7f61"
authors = ["Peter Deffebach <p.deffebach@gmail.com> and contributors"]
version = "0.1.0"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
MacroTools = "0.5"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
